vim.g.mapleader=" "
vim.keymap.set("n", "<leader>pv", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "<C-j>","<C-W>j")
vim.keymap.set("n", "<C-k>","<C-W>k")
vim.keymap.set("n", "<C-h>","<C-W>h")
vim.keymap.set("n", "<C-l>","<C-W>l")
vim.keymap.set("n", "O","O<Esc>")
vim.keymap.set("n", "o","o<Esc>")
vim.keymap.set("n", "d", "\"_d")
vim.keymap.set("n", "dd", "\"_dd")
vim.keymap.set("n", "<C-j>", "<C-e>")
vim.keymap.set("n", "<C-k>", "<C-y>")
vim.keymap.set("n", "<Tab>", "<C-w>w")
vim.keymap.set("v", "y", "\"*y")
vim.keymap.set("v", "p", "\"*p")
vim.keymap.set("v","<C-C>", "\"+y")
