vim.api.nvim_set_hl(0, 'FloatBorder', {ctermbg='white'})
vim.api.nvim_set_hl(0, 'NormalFloat', {ctermbg=''})
vim.api.nvim_set_hl(1, 'TelescopeNormal', {ctermbg='red'})
vim.api.nvim_set_hl(1, 'TelescopeBorder', {ctermbg='red'})
vim.wo.number=true
vim.api.nvim_set_hl(0, 'LineNr', {ctermfg="grey",fg="black"})
vim.api.nvim_set_hl(0,'identifier',{ctermfg="cyan",fg="black",bold=false})
vim.api.nvim_set_hl(0,'function',{ctermfg='green'})
vim.api.nvim_set_hl(0,'pmenu',{ctermbg=''})
vim.api.nvim_set_hl(0,'delimiter',{ctermfg="grey"})
vim.api.nvim_set_hl(0,"specialchar",{ctermfg="red"})
vim.api.nvim_set_hl(0,"special",{ctermfg="green"})
vim.api.nvim_set_hl(0,"constant",{ctermfg="magenta"})
vim.api.nvim_set_hl(0,"comment",{ctermfg="grey",fg="black"})
vim.api.nvim_set_hl(0,"type",{ctermfg="red"})
vim.api.nvim_set_hl(0,"preproc",{ctermfg="yellow"})
vim.api.nvim_set_hl(0,"operator",{ctermfg="grey"})
vim.api.nvim_set_hl(0,"matchparen",{ctermfg="black",ctermbg="white",underline=false})
vim.api.nvim_set_hl(0,"pmenuthumb",{ctermfg="white",ctermbg="cyan"})
vim.api.nvim_set_hl(0, "signcolumn",{ctermbg=""})
vim.api.nvim_set_hl(0,"directory",{ctermfg="cyan"})
vim.api.nvim_set_hl(0,"Iblindent",{ctermfg=0})
vim.api.nvim_set_hl(0,"TSTitle", {ctermfg="green"})
vim.api.nvim_set_hl(0,"@markup.heading.1", {ctermfg=14})
vim.api.nvim_set_hl(0,"@markup.heading.2", {ctermfg=12})
vim.api.nvim_set_hl(0,"@markup.heading.3", {ctermfg=11})
vim.api.nvim_set_hl(0,"@markup.heading.4", {ctermfg=13})
vim.api.nvim_set_hl(0,"@markup.heading.5", {ctermfg=10})
vim.api.nvim_set_hl(0,"@markup.heading.6", {ctermfg=9})
vim.api.nvim_set_hl(0,"IndentBlanklineIndent1", {ctermfg="green"})
